version: '3.9'

networks:
  bridge:
    driver: bridge

services:
  nginx:
    image: nginx:1.22
    networks:
      - bridge
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - php

  php:
    image: php:8.2.6-fpm
    networks:
      - bridge
    links:
      - mysql
    volumes:
      - ./laravel:/var/www/html
      - ./vendor:/var/www/html/vendor
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    networks:
      - bridge
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password