

networks:
  bridge:
    driver: bridge

services:
  react_app:
    build:
      context: ./react_app
      dockerfile: Dockerfile
    
    container_name: container_r

    networks:
      - bridge
    links:
      - mysql
    ports:
      - "3001:3000"
    volumes:
      - ./react_app:/app
      - /app/node_modules
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: container_db
    networks:
      - bridge
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password