

networks:
  bridge:
    driver: bridge

services:
  react_app:
    build:
      context: react_app
      target: development
    networks:
      - bridge
    links:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - ./react_app/src:/code/src
      - /code/node_modules
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    networks:
      - bridge
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password